import ORMManager from "slintorm";
import type { Workspace } from "./workspace";
import type { User } from "./user";
import type { Branch } from "./branch";
import type { Contact } from "./contact";
import type { Deal } from "./deal";
import type { Activity } from "./activity";
import type { Product } from "./product";
import type { Order } from "./order";
import type { OrderItem } from "./orderItem";
import type { Invoice } from "./invoice";
import type { Employee } from "./employee";
import type { Attendance } from "./attendance";
import type { LeaveRequest } from "./leaveRequest";
import type { EmailCampaign } from "./emailCampaign";
import type { EmailTemplate } from "./emailTemplate";
import type { LandingPage } from "./landingPage";
import type { Form } from "./form";
import type { FormSubmission } from "./formSubmission";
import type { SocialAccount } from "./socialAccount";
import type { SocialPost } from "./socialPost";
import type { SocialReply } from "./socialReply";
import type { AdCampaign } from "./adCampaign";
import type { WordpressSite } from "./wordpressSite";
import type { WordpressPost } from "./wordpressPost";
import type { Message } from "./message";
import type { Call } from "./call";
import type { Meeting } from "./meeting";
import type { Ticket } from "./ticket";
import type { TicketMessage } from "./ticketMessage";
import type { Document } from "./document";
import type { Notification } from "./notification";
import type { AuditLog } from "./auditLog";
import type { CustomFieldDef } from "./customFieldDef";
import type { CustomFieldValue } from "./customFieldValue";
import type { Workflow } from "./workflow";
import type { EmailSync } from "./emailSync";
import type { LiveChatSettings } from "./liveChatSettings";
import type { ChatMessage } from "./chatMessage";
import type { Project } from "./project";
import type { ProjectTask } from "./projectTask";
import type { ProjectMilestone } from "./projectMilestone";
import type { Bot } from "./bot";
import type { WidgetSettings } from "./widgetSettings";
import type { AIApiKey } from "./aIApiKey";
import type { AIConversation } from "./aIConversation";
import type { AIAction } from "./aIAction";
import type { BotConnection } from "./botConnection";
import type { HealthScore } from "./healthScore";
import type { NPSResponse } from "./nPSResponse";
import type { CSATResponse } from "./cSATResponse";
import type { OnboardingTask } from "./onboardingTask";
import type { ChurnPrediction } from "./churnPrediction";
import type { SalesPipeline } from "./salesPipeline";
import type { SalesGoal } from "./salesGoal";
import type { CommissionPlan } from "./commissionPlan";
import type { CommissionEarning } from "./commissionEarning";
import type { Quote } from "./quote";
import type { QuoteLineItem } from "./quoteLineItem";
import type { ProductDiscount } from "./productDiscount";
import type { Territory } from "./territory";
import type { Subscription } from "./subscription";
import type { SubscriptionPlan } from "./subscriptionPlan";
import type { SubscriptionInvoice } from "./subscriptionInvoice";
import type { ABTest } from "./aBTest";
import type { MarketingSegment } from "./marketingSegment";
import type { LeadScoreRule } from "./leadScoreRule";
import type { MarketingJourney } from "./marketingJourney";
import type { SMSCampaign } from "./sMSCampaign";
import type { PushNotification } from "./pushNotification";
import type { SocialMention } from "./socialMention";
import type { UTMLink } from "./uTMLink";
import type { SEOConfig } from "./sEOConfig";
import type { KnowledgeArticle } from "./knowledgeArticle";
import type { FAQItem } from "./fAQItem";
import type { ForumTopic } from "./forumTopic";
import type { ForumPost } from "./forumPost";
import type { SLAPolicy } from "./sLAPolicy";
import type { CannedResponse } from "./cannedResponse";
import type { Macro } from "./macro";
import type { EscalationRule } from "./escalationRule";
import type { Asset } from "./asset";
import type { WorkflowTemplate } from "./workflowTemplate";
import type { WorkflowVersion } from "./workflowVersion";
import type { CustomDashboard } from "./customDashboard";
import type { ScheduledReport } from "./scheduledReport";
import type { CohortData } from "./cohortData";
import type { CLVCalculation } from "./cLVCalculation";
import type { TwoFactorSetting } from "./twoFactorSetting";
import type { UserDevice } from "./userDevice";
import type { IPAllowlistEntry } from "./iPAllowlistEntry";
import type { WebhookEndpoint } from "./webhookEndpoint";
import type { OAuthApp } from "./oAuthApp";
import type { APILogEntry } from "./aPILogEntry";
import type { InternalComment } from "./internalComment";
import type { SharedNote } from "./sharedNote";
import type { Whiteboard } from "./whiteboard";
import type { Expense } from "./expense";
import type { PaymentGateway } from "./paymentGateway";
import type { TaxRate } from "./taxRate";
import type { Refund } from "./refund";
import type { CalendarEvent } from "./calendarEvent";
import type { BookingLink } from "./bookingLink";
import type { CalendarSync } from "./calendarSync";
import type { BrandingConfig } from "./brandingConfig";
import type { CustomDomain } from "./customDomain";
import type { FeatureFlag } from "./featureFlag";
import type { BackupRecord } from "./backupRecord";
import type { DataRetentionPolicy } from "./dataRetentionPolicy";
import type { AuditSetting } from "./auditSetting";
import type { BackgroundJob } from "./backgroundJob";
import type { WebhookDelivery } from "./webhookDelivery";
import type { EmailDelivery } from "./emailDelivery";
import type { SystemHealthMetric } from "./systemHealthMetric";
import type { WorkspaceQuota } from "./workspaceQuota";
import type { UsageRecord } from "./usageRecord";
import type { LanguagePack } from "./languagePack";
import type { TranslationEntry } from "./translationEntry";
import type { MarketplaceListing } from "./marketplaceListing";
import type { MarketplaceReview } from "./marketplaceReview";
import type { InstalledItem } from "./installedItem";
import type { Plugin } from "./plugin";
import type { PluginExtension } from "./pluginExtension";
import type { PaystackPayment } from "./paystackPayment";
import type { JobPosting } from "./jobPosting";
import type { Candidate } from "./candidate";
import type { JobApplication } from "./jobApplication";
import type { Interview } from "./interview";
import type { OfferLetter } from "./offerLetter";
import type { HiringMetric } from "./hiringMetric";
import type { HiringStage } from "./hiringStage";
import type { StaffDepartment } from "./staffDepartment";
import type { StaffPosition } from "./staffPosition";
import type { StaffShift } from "./staffShift";
import type { StaffSchedule } from "./staffSchedule";
import type { StaffTimesheet } from "./staffTimesheet";
import type { StaffAttendanceRecord } from "./staffAttendanceRecord";
import type { StaffLeaveType } from "./staffLeaveType";
import type { StaffLeaveRequest } from "./staffLeaveRequest";
import type { StaffPerformanceReview } from "./staffPerformanceReview";
import type { StaffGoal } from "./staffGoal";
import type { StaffTrainingCourse } from "./staffTrainingCourse";
import type { StaffTrainingEnrollment } from "./staffTrainingEnrollment";
import type { StaffCertification } from "./staffCertification";
import type { StaffSkill } from "./staffSkill";
import type { StaffEmployeeSkill } from "./staffEmployeeSkill";
import type { StaffDocument } from "./staffDocument";
import type { StaffComplianceItem } from "./staffComplianceItem";
import type { StaffDisciplinaryAction } from "./staffDisciplinaryAction";
import type { StaffExpenseReport } from "./staffExpenseReport";
import type { InventoryWarehouse } from "./inventoryWarehouse";
import type { InventoryCategory } from "./inventoryCategory";
import type { InventoryBrand } from "./inventoryBrand";
import type { InventoryItem } from "./inventoryItem";
import type { InventoryVariant } from "./inventoryVariant";
import type { InventoryStock } from "./inventoryStock";
import type { InventoryMovement } from "./inventoryMovement";
import type { InventorySupplier } from "./inventorySupplier";
import type { InventoryPurchaseOrder } from "./inventoryPurchaseOrder";
import type { InventoryPurchaseOrderItem } from "./inventoryPurchaseOrderItem";
import type { InventoryGoodsReceivedNote } from "./inventoryGoodsReceivedNote";
import type { InventoryStockTransfer } from "./inventoryStockTransfer";
import type { InventoryStockCount } from "./inventoryStockCount";
import type { InventoryReorderRule } from "./inventoryReorderRule";
import type { InventoryBatch } from "./inventoryBatch";
import type { InventoryReturn } from "./inventoryReturn";
import type { InventoryCostHistory } from "./inventoryCostHistory";
import type { DepartmentModule } from "./departmentModule";
import type { Task } from "./task";
import type { DepartmentModuleAssignment } from "./departmentModuleAssignment";

export type { Workspace } from "./workspace";
export type { User } from "./user";
export type { Branch } from "./branch";
export type { Contact } from "./contact";
export type { Deal } from "./deal";
export type { Activity } from "./activity";
export type { Product } from "./product";
export type { Order } from "./order";
export type { OrderItem } from "./orderItem";
export type { Invoice } from "./invoice";
export type { Employee } from "./employee";
export type { Attendance } from "./attendance";
export type { LeaveRequest } from "./leaveRequest";
export type { EmailCampaign } from "./emailCampaign";
export type { EmailTemplate } from "./emailTemplate";
export type { LandingPage } from "./landingPage";
export type { Form } from "./form";
export type { FormSubmission } from "./formSubmission";
export type { SocialAccount } from "./socialAccount";
export type { SocialPost } from "./socialPost";
export type { SocialReply } from "./socialReply";
export type { AdCampaign } from "./adCampaign";
export type { WordpressSite } from "./wordpressSite";
export type { WordpressPost } from "./wordpressPost";
export type { Message } from "./message";
export type { Call } from "./call";
export type { Meeting } from "./meeting";
export type { Ticket } from "./ticket";
export type { TicketMessage } from "./ticketMessage";
export type { Document } from "./document";
export type { Notification } from "./notification";
export type { AuditLog } from "./auditLog";
export type { CustomFieldDef } from "./customFieldDef";
export type { CustomFieldValue } from "./customFieldValue";
export type { Workflow } from "./workflow";
export type { EmailSync } from "./emailSync";
export type { LiveChatSettings } from "./liveChatSettings";
export type { ChatMessage } from "./chatMessage";
export type { Project } from "./project";
export type { ProjectTask } from "./projectTask";
export type { ProjectMilestone } from "./projectMilestone";
export type { Bot } from "./bot";
export type { WidgetSettings } from "./widgetSettings";
export type { AIApiKey } from "./aIApiKey";
export type { AIConversation } from "./aIConversation";
export type { AIAction } from "./aIAction";
export type { BotConnection } from "./botConnection";
export type { HealthScore } from "./healthScore";
export type { NPSResponse } from "./nPSResponse";
export type { CSATResponse } from "./cSATResponse";
export type { OnboardingTask } from "./onboardingTask";
export type { ChurnPrediction } from "./churnPrediction";
export type { SalesPipeline } from "./salesPipeline";
export type { SalesGoal } from "./salesGoal";
export type { CommissionPlan } from "./commissionPlan";
export type { CommissionEarning } from "./commissionEarning";
export type { Quote } from "./quote";
export type { QuoteLineItem } from "./quoteLineItem";
export type { ProductDiscount } from "./productDiscount";
export type { Territory } from "./territory";
export type { Subscription } from "./subscription";
export type { SubscriptionPlan } from "./subscriptionPlan";
export type { SubscriptionInvoice } from "./subscriptionInvoice";
export type { ABTest } from "./aBTest";
export type { MarketingSegment } from "./marketingSegment";
export type { LeadScoreRule } from "./leadScoreRule";
export type { MarketingJourney } from "./marketingJourney";
export type { SMSCampaign } from "./sMSCampaign";
export type { PushNotification } from "./pushNotification";
export type { SocialMention } from "./socialMention";
export type { UTMLink } from "./uTMLink";
export type { SEOConfig } from "./sEOConfig";
export type { KnowledgeArticle } from "./knowledgeArticle";
export type { FAQItem } from "./fAQItem";
export type { ForumTopic } from "./forumTopic";
export type { ForumPost } from "./forumPost";
export type { SLAPolicy } from "./sLAPolicy";
export type { CannedResponse } from "./cannedResponse";
export type { Macro } from "./macro";
export type { EscalationRule } from "./escalationRule";
export type { Asset } from "./asset";
export type { WorkflowTemplate } from "./workflowTemplate";
export type { WorkflowVersion } from "./workflowVersion";
export type { CustomDashboard } from "./customDashboard";
export type { ScheduledReport } from "./scheduledReport";
export type { CohortData } from "./cohortData";
export type { CLVCalculation } from "./cLVCalculation";
export type { TwoFactorSetting } from "./twoFactorSetting";
export type { UserDevice } from "./userDevice";
export type { IPAllowlistEntry } from "./iPAllowlistEntry";
export type { WebhookEndpoint } from "./webhookEndpoint";
export type { OAuthApp } from "./oAuthApp";
export type { APILogEntry } from "./aPILogEntry";
export type { InternalComment } from "./internalComment";
export type { SharedNote } from "./sharedNote";
export type { Whiteboard } from "./whiteboard";
export type { Expense } from "./expense";
export type { PaymentGateway } from "./paymentGateway";
export type { TaxRate } from "./taxRate";
export type { Refund } from "./refund";
export type { CalendarEvent } from "./calendarEvent";
export type { BookingLink } from "./bookingLink";
export type { CalendarSync } from "./calendarSync";
export type { BrandingConfig } from "./brandingConfig";
export type { CustomDomain } from "./customDomain";
export type { FeatureFlag } from "./featureFlag";
export type { BackupRecord } from "./backupRecord";
export type { DataRetentionPolicy } from "./dataRetentionPolicy";
export type { AuditSetting } from "./auditSetting";
export type { BackgroundJob } from "./backgroundJob";
export type { WebhookDelivery } from "./webhookDelivery";
export type { EmailDelivery } from "./emailDelivery";
export type { SystemHealthMetric } from "./systemHealthMetric";
export type { WorkspaceQuota } from "./workspaceQuota";
export type { UsageRecord } from "./usageRecord";
export type { LanguagePack } from "./languagePack";
export type { TranslationEntry } from "./translationEntry";
export type { MarketplaceListing } from "./marketplaceListing";
export type { MarketplaceReview } from "./marketplaceReview";
export type { InstalledItem } from "./installedItem";
export type { Plugin } from "./plugin";
export type { PluginExtension } from "./pluginExtension";
export type { PaystackPayment } from "./paystackPayment";
export type { JobPosting } from "./jobPosting";
export type { Candidate } from "./candidate";
export type { JobApplication } from "./jobApplication";
export type { Interview } from "./interview";
export type { OfferLetter } from "./offerLetter";
export type { HiringMetric } from "./hiringMetric";
export type { HiringStage } from "./hiringStage";
export type { StaffDepartment } from "./staffDepartment";
export type { StaffPosition } from "./staffPosition";
export type { StaffShift } from "./staffShift";
export type { StaffSchedule } from "./staffSchedule";
export type { StaffTimesheet } from "./staffTimesheet";
export type { StaffAttendanceRecord } from "./staffAttendanceRecord";
export type { StaffLeaveType } from "./staffLeaveType";
export type { StaffLeaveRequest } from "./staffLeaveRequest";
export type { StaffPerformanceReview } from "./staffPerformanceReview";
export type { StaffGoal } from "./staffGoal";
export type { StaffTrainingCourse } from "./staffTrainingCourse";
export type { StaffTrainingEnrollment } from "./staffTrainingEnrollment";
export type { StaffCertification } from "./staffCertification";
export type { StaffSkill } from "./staffSkill";
export type { StaffEmployeeSkill } from "./staffEmployeeSkill";
export type { StaffDocument } from "./staffDocument";
export type { StaffComplianceItem } from "./staffComplianceItem";
export type { StaffDisciplinaryAction } from "./staffDisciplinaryAction";
export type { StaffExpenseReport } from "./staffExpenseReport";
export type { InventoryWarehouse } from "./inventoryWarehouse";
export type { InventoryCategory } from "./inventoryCategory";
export type { InventoryBrand } from "./inventoryBrand";
export type { InventoryItem } from "./inventoryItem";
export type { InventoryVariant } from "./inventoryVariant";
export type { InventoryStock } from "./inventoryStock";
export type { InventoryMovement } from "./inventoryMovement";
export type { InventorySupplier } from "./inventorySupplier";
export type { InventoryPurchaseOrder } from "./inventoryPurchaseOrder";
export type { InventoryPurchaseOrderItem } from "./inventoryPurchaseOrderItem";
export type { InventoryGoodsReceivedNote } from "./inventoryGoodsReceivedNote";
export type { InventoryStockTransfer } from "./inventoryStockTransfer";
export type { InventoryStockCount } from "./inventoryStockCount";
export type { InventoryReorderRule } from "./inventoryReorderRule";
export type { InventoryBatch } from "./inventoryBatch";
export type { InventoryReturn } from "./inventoryReturn";
export type { InventoryCostHistory } from "./inventoryCostHistory";
export type { DepartmentModule } from "./departmentModule";
export type { DepartmentModuleAssignment } from "./departmentModuleAssignment";

export type ModelMap = {
  Workspace: Workspace;
  User: User;
  Branch: Branch;
  Contact: Contact;
  Deal: Deal;
  Activity: Activity;
  Product: Product;
  Order: Order;
  OrderItem: OrderItem;
  Invoice: Invoice;
  Employee: Employee;
  Attendance: Attendance;
  LeaveRequest: LeaveRequest;
  EmailCampaign: EmailCampaign;
  EmailTemplate: EmailTemplate;
  LandingPage: LandingPage;
  Form: Form;
  FormSubmission: FormSubmission;
  SocialAccount: SocialAccount;
  SocialPost: SocialPost;
  SocialReply: SocialReply;
  AdCampaign: AdCampaign;
  WordpressSite: WordpressSite;
  WordpressPost: WordpressPost;
  Message: Message;
  Call: Call;
  Meeting: Meeting;
  Ticket: Ticket;
  TicketMessage: TicketMessage;
  Document: Document;
  Notification: Notification;
  AuditLog: AuditLog;
  CustomFieldDef: CustomFieldDef;
  CustomFieldValue: CustomFieldValue;
  Workflow: Workflow;
  EmailSync: EmailSync;
  LiveChatSettings: LiveChatSettings;
  ChatMessage: ChatMessage;
  Project: Project;
  ProjectTask: ProjectTask;
  ProjectMilestone: ProjectMilestone;
  Bot: Bot;
  WidgetSettings: WidgetSettings;
  AIApiKey: AIApiKey;
  AIConversation: AIConversation;
  AIAction: AIAction;
  BotConnection: BotConnection;
  HealthScore: HealthScore;
  NPSResponse: NPSResponse;
  CSATResponse: CSATResponse;
  OnboardingTask: OnboardingTask;
  ChurnPrediction: ChurnPrediction;
  SalesPipeline: SalesPipeline;
  SalesGoal: SalesGoal;
  CommissionPlan: CommissionPlan;
  CommissionEarning: CommissionEarning;
  Quote: Quote;
  QuoteLineItem: QuoteLineItem;
  ProductDiscount: ProductDiscount;
  Territory: Territory;
  Subscription: Subscription;
  SubscriptionPlan: SubscriptionPlan;
  SubscriptionInvoice: SubscriptionInvoice;
  ABTest: ABTest;
  MarketingSegment: MarketingSegment;
  LeadScoreRule: LeadScoreRule;
  MarketingJourney: MarketingJourney;
  SMSCampaign: SMSCampaign;
  PushNotification: PushNotification;
  SocialMention: SocialMention;
  UTMLink: UTMLink;
  SEOConfig: SEOConfig;
  KnowledgeArticle: KnowledgeArticle;
  FAQItem: FAQItem;
  ForumTopic: ForumTopic;
  ForumPost: ForumPost;
  SLAPolicy: SLAPolicy;
  CannedResponse: CannedResponse;
  Macro: Macro;
  EscalationRule: EscalationRule;
  Asset: Asset;
  WorkflowTemplate: WorkflowTemplate;
  WorkflowVersion: WorkflowVersion;
  CustomDashboard: CustomDashboard;
  ScheduledReport: ScheduledReport;
  CohortData: CohortData;
  CLVCalculation: CLVCalculation;
  TwoFactorSetting: TwoFactorSetting;
  UserDevice: UserDevice;
  IPAllowlistEntry: IPAllowlistEntry;
  WebhookEndpoint: WebhookEndpoint;
  OAuthApp: OAuthApp;
  APILogEntry: APILogEntry;
  InternalComment: InternalComment;
  SharedNote: SharedNote;
  Whiteboard: Whiteboard;
  Expense: Expense;
  PaymentGateway: PaymentGateway;
  TaxRate: TaxRate;
  Refund: Refund;
  CalendarEvent: CalendarEvent;
  BookingLink: BookingLink;
  CalendarSync: CalendarSync;
  BrandingConfig: BrandingConfig;
  CustomDomain: CustomDomain;
  FeatureFlag: FeatureFlag;
  BackupRecord: BackupRecord;
  DataRetentionPolicy: DataRetentionPolicy;
  AuditSetting: AuditSetting;
  BackgroundJob: BackgroundJob;
  WebhookDelivery: WebhookDelivery;
  EmailDelivery: EmailDelivery;
  SystemHealthMetric: SystemHealthMetric;
  WorkspaceQuota: WorkspaceQuota;
  UsageRecord: UsageRecord;
  LanguagePack: LanguagePack;
  TranslationEntry: TranslationEntry;
  MarketplaceListing: MarketplaceListing;
  MarketplaceReview: MarketplaceReview;
  InstalledItem: InstalledItem;
  Plugin: Plugin;
  PluginExtension: PluginExtension;
  PaystackPayment: PaystackPayment;
  JobPosting: JobPosting;
  Candidate: Candidate;
  JobApplication: JobApplication;
  Interview: Interview;
  OfferLetter: OfferLetter;
  HiringMetric: HiringMetric;
  HiringStage: HiringStage;
  StaffDepartment: StaffDepartment;
  StaffPosition: StaffPosition;
  StaffShift: StaffShift;
  StaffSchedule: StaffSchedule;
  StaffTimesheet: StaffTimesheet;
  StaffAttendanceRecord: StaffAttendanceRecord;
  StaffLeaveType: StaffLeaveType;
  StaffLeaveRequest: StaffLeaveRequest;
  StaffPerformanceReview: StaffPerformanceReview;
  StaffGoal: StaffGoal;
  StaffTrainingCourse: StaffTrainingCourse;
  StaffTrainingEnrollment: StaffTrainingEnrollment;
  StaffCertification: StaffCertification;
  StaffSkill: StaffSkill;
  StaffEmployeeSkill: StaffEmployeeSkill;
  StaffDocument: StaffDocument;
  StaffComplianceItem: StaffComplianceItem;
  StaffDisciplinaryAction: StaffDisciplinaryAction;
  StaffExpenseReport: StaffExpenseReport;
  InventoryWarehouse: InventoryWarehouse;
  InventoryCategory: InventoryCategory;
  InventoryBrand: InventoryBrand;
  InventoryItem: InventoryItem;
  InventoryVariant: InventoryVariant;
  InventoryStock: InventoryStock;
  InventoryMovement: InventoryMovement;
  InventorySupplier: InventorySupplier;
  InventoryPurchaseOrder: InventoryPurchaseOrder;
  InventoryPurchaseOrderItem: InventoryPurchaseOrderItem;
  InventoryGoodsReceivedNote: InventoryGoodsReceivedNote;
  InventoryStockTransfer: InventoryStockTransfer;
  InventoryStockCount: InventoryStockCount;
  InventoryReorderRule: InventoryReorderRule;
  InventoryBatch: InventoryBatch;
  InventoryReturn: InventoryReturn;
  InventoryCostHistory: InventoryCostHistory;
  DepartmentModule: DepartmentModule;
  DepartmentModuleAssignment: DepartmentModuleAssignment;
  Task: Task;
};

export function registerModels(orm: ORMManager<ModelMap>) {
  orm.defineModel<Workspace>('workspaces', 'Workspace');
  orm.defineModel<User>('users', 'User');
  orm.defineModel<Branch>('branches', 'Branch');
  orm.defineModel<Contact>('contacts', 'Contact');
  orm.defineModel<Deal>('deals', 'Deal');
  orm.defineModel<Activity>('activities', 'Activity');
  orm.defineModel<Product>('products', 'Product');
  orm.defineModel<Order>('orders', 'Order');
  orm.defineModel<OrderItem>('order_items', 'OrderItem');
  orm.defineModel<Invoice>('invoices', 'Invoice');
  orm.defineModel<Employee>('employees', 'Employee');
  orm.defineModel<Attendance>('attendance', 'Attendance');
  orm.defineModel<LeaveRequest>('leave_requests', 'LeaveRequest');
  orm.defineModel<EmailCampaign>('email_campaigns', 'EmailCampaign');
  orm.defineModel<EmailTemplate>('email_templates', 'EmailTemplate');
  orm.defineModel<LandingPage>('landing_pages', 'LandingPage');
  orm.defineModel<Form>('forms', 'Form');
  orm.defineModel<FormSubmission>('form_submissions', 'FormSubmission');
  orm.defineModel<SocialAccount>('social_accounts', 'SocialAccount');
  orm.defineModel<SocialPost>('social_posts', 'SocialPost');
  orm.defineModel<SocialReply>('social_replies', 'SocialReply');
  orm.defineModel<AdCampaign>('ad_campaigns', 'AdCampaign');
  orm.defineModel<WordpressSite>('wordpress_sites', 'WordpressSite');
  orm.defineModel<WordpressPost>('wordpress_posts', 'WordpressPost');
  orm.defineModel<Message>('messages', 'Message');
  orm.defineModel<Call>('calls', 'Call');
  orm.defineModel<Meeting>('meetings', 'Meeting');
  orm.defineModel<Ticket>('tickets', 'Ticket');
  orm.defineModel<TicketMessage>('ticket_messages', 'TicketMessage');
  orm.defineModel<Document>('documents', 'Document');
  orm.defineModel<Notification>('notifications', 'Notification');
  orm.defineModel<AuditLog>('audit_logs', 'AuditLog');
  orm.defineModel<CustomFieldDef>('custom_field_defs', 'CustomFieldDef');
  orm.defineModel<CustomFieldValue>('custom_field_values', 'CustomFieldValue');
  orm.defineModel<Workflow>('workflows', 'Workflow');
  orm.defineModel<EmailSync>('email_syncs', 'EmailSync');
  orm.defineModel<LiveChatSettings>('live_chat_settings', 'LiveChatSettings');
  orm.defineModel<ChatMessage>('chat_messages', 'ChatMessage');
  orm.defineModel<Project>('projects', 'Project');
  orm.defineModel<ProjectTask>('project_tasks', 'ProjectTask');
  orm.defineModel<ProjectMilestone>('project_milestones', 'ProjectMilestone');
  orm.defineModel<Bot>('bots', 'Bot');
  orm.defineModel<WidgetSettings>('widget_settings', 'WidgetSettings');
  orm.defineModel<AIApiKey>('ai_api_keys', 'AIApiKey');
  orm.defineModel<AIConversation>('ai_conversations', 'AIConversation');
  orm.defineModel<AIAction>('ai_actions', 'AIAction');
  orm.defineModel<BotConnection>('bot_connections', 'BotConnection');
  orm.defineModel<HealthScore>('health_scores', 'HealthScore');
  orm.defineModel<NPSResponse>('nps_responses', 'NPSResponse');
  orm.defineModel<CSATResponse>('csat_responses', 'CSATResponse');
  orm.defineModel<OnboardingTask>('onboarding_tasks', 'OnboardingTask');
  orm.defineModel<ChurnPrediction>('churn_predictions', 'ChurnPrediction');
  orm.defineModel<SalesPipeline>('sales_pipelines', 'SalesPipeline');
  orm.defineModel<SalesGoal>('sales_goals', 'SalesGoal');
  orm.defineModel<CommissionPlan>('commission_plans', 'CommissionPlan');
  orm.defineModel<CommissionEarning>('commission_earnings', 'CommissionEarning');
  orm.defineModel<Quote>('quotes', 'Quote');
  orm.defineModel<QuoteLineItem>('quote_line_items', 'QuoteLineItem');
  orm.defineModel<ProductDiscount>('product_discounts', 'ProductDiscount');
  orm.defineModel<Territory>('territories', 'Territory');
  orm.defineModel<Subscription>('subscriptions', 'Subscription');
  orm.defineModel<SubscriptionPlan>('subscription_plans', 'SubscriptionPlan');
  orm.defineModel<SubscriptionInvoice>('subscription_invoices', 'SubscriptionInvoice');
  orm.defineModel<ABTest>('ab_tests', 'ABTest');
  orm.defineModel<MarketingSegment>('marketing_segments', 'MarketingSegment');
  orm.defineModel<LeadScoreRule>('lead_score_rules', 'LeadScoreRule');
  orm.defineModel<MarketingJourney>('marketing_journeys', 'MarketingJourney');
  orm.defineModel<SMSCampaign>('sms_campaigns', 'SMSCampaign');
  orm.defineModel<PushNotification>('push_notifications', 'PushNotification');
  orm.defineModel<SocialMention>('social_mentions', 'SocialMention');
  orm.defineModel<UTMLink>('utm_links', 'UTMLink');
  orm.defineModel<SEOConfig>('seo_configs', 'SEOConfig');
  orm.defineModel<KnowledgeArticle>('knowledge_articles', 'KnowledgeArticle');
  orm.defineModel<FAQItem>('faq_items', 'FAQItem');
  orm.defineModel<ForumTopic>('forum_topics', 'ForumTopic');
  orm.defineModel<ForumPost>('forum_posts', 'ForumPost');
  orm.defineModel<SLAPolicy>('sla_policies', 'SLAPolicy');
  orm.defineModel<CannedResponse>('canned_responses', 'CannedResponse');
  orm.defineModel<Macro>('macros', 'Macro');
  orm.defineModel<EscalationRule>('escalation_rules', 'EscalationRule');
  orm.defineModel<Asset>('assets', 'Asset');
  orm.defineModel<WorkflowTemplate>('workflow_templates', 'WorkflowTemplate');
  orm.defineModel<WorkflowVersion>('workflow_versions', 'WorkflowVersion');
  orm.defineModel<CustomDashboard>('custom_dashboards', 'CustomDashboard');
  orm.defineModel<ScheduledReport>('scheduled_reports', 'ScheduledReport');
  orm.defineModel<CohortData>('cohort_data', 'CohortData');
  orm.defineModel<CLVCalculation>('clv_calculations', 'CLVCalculation');
  orm.defineModel<TwoFactorSetting>('two_factor_settings', 'TwoFactorSetting');
  orm.defineModel<UserDevice>('user_devices', 'UserDevice');
  orm.defineModel<IPAllowlistEntry>('ip_allowlist_entries', 'IPAllowlistEntry');
  orm.defineModel<WebhookEndpoint>('webhook_endpoints', 'WebhookEndpoint');
  orm.defineModel<OAuthApp>('oauth_apps', 'OAuthApp');
  orm.defineModel<APILogEntry>('api_log_entries', 'APILogEntry');
  orm.defineModel<InternalComment>('internal_comments', 'InternalComment');
  orm.defineModel<SharedNote>('shared_notes', 'SharedNote');
  orm.defineModel<Whiteboard>('whiteboards', 'Whiteboard');
  orm.defineModel<Expense>('expenses', 'Expense');
  orm.defineModel<PaymentGateway>('payment_gateways', 'PaymentGateway');
  orm.defineModel<TaxRate>('tax_rates', 'TaxRate');
  orm.defineModel<Refund>('refunds', 'Refund');
  orm.defineModel<CalendarEvent>('calendar_events', 'CalendarEvent');
  orm.defineModel<BookingLink>('booking_links', 'BookingLink');
  orm.defineModel<CalendarSync>('calendar_syncs', 'CalendarSync');
  orm.defineModel<BrandingConfig>('branding_configs', 'BrandingConfig');
  orm.defineModel<CustomDomain>('custom_domains', 'CustomDomain');
  orm.defineModel<FeatureFlag>('feature_flags', 'FeatureFlag');
  orm.defineModel<BackupRecord>('backup_records', 'BackupRecord');
  orm.defineModel<DataRetentionPolicy>('data_retention_policies', 'DataRetentionPolicy');
  orm.defineModel<AuditSetting>('audit_settings', 'AuditSetting');
  orm.defineModel<BackgroundJob>('background_jobs', 'BackgroundJob');
  orm.defineModel<WebhookDelivery>('webhook_deliveries', 'WebhookDelivery');
  orm.defineModel<EmailDelivery>('email_deliveries', 'EmailDelivery');
  orm.defineModel<SystemHealthMetric>('system_health_metrics', 'SystemHealthMetric');
  orm.defineModel<WorkspaceQuota>('workspace_quotas', 'WorkspaceQuota');
  orm.defineModel<UsageRecord>('usage_records', 'UsageRecord');
  orm.defineModel<LanguagePack>('language_packs', 'LanguagePack');
  orm.defineModel<TranslationEntry>('translation_entries', 'TranslationEntry');
  orm.defineModel<MarketplaceListing>('marketplace_listings', 'MarketplaceListing');
  orm.defineModel<MarketplaceReview>('marketplace_reviews', 'MarketplaceReview');
  orm.defineModel<InstalledItem>('installed_items', 'InstalledItem');
  orm.defineModel<Plugin>('plugins', 'Plugin');
  orm.defineModel<PluginExtension>('plugin_extensions', 'PluginExtension');
  orm.defineModel<PaystackPayment>('paystack_payments', 'PaystackPayment');
  orm.defineModel<JobPosting>('job_postings', 'JobPosting');
  orm.defineModel<Candidate>('candidates', 'Candidate');
  orm.defineModel<JobApplication>('job_applications', 'JobApplication');
  orm.defineModel<Interview>('interviews', 'Interview');
  orm.defineModel<OfferLetter>('offer_letters', 'OfferLetter');
  orm.defineModel<HiringMetric>('hiring_metrics', 'HiringMetric');
  orm.defineModel<HiringStage>('hiring_stages', 'HiringStage');
  orm.defineModel<StaffDepartment>('staff_departments', 'StaffDepartment');
  orm.defineModel<StaffPosition>('staff_positions', 'StaffPosition');
  orm.defineModel<StaffShift>('staff_shifts', 'StaffShift');
  orm.defineModel<StaffSchedule>('staff_schedules', 'StaffSchedule');
  orm.defineModel<StaffTimesheet>('staff_timesheets', 'StaffTimesheet');
  orm.defineModel<StaffAttendanceRecord>('staff_attendance_records', 'StaffAttendanceRecord');
  orm.defineModel<StaffLeaveType>('staff_leave_types', 'StaffLeaveType');
  orm.defineModel<StaffLeaveRequest>('staff_leave_requests', 'StaffLeaveRequest');
  orm.defineModel<StaffPerformanceReview>('staff_performance_reviews', 'StaffPerformanceReview');
  orm.defineModel<StaffGoal>('staff_goals', 'StaffGoal');
  orm.defineModel<StaffTrainingCourse>('staff_training_courses', 'StaffTrainingCourse');
  orm.defineModel<StaffTrainingEnrollment>('staff_training_enrollments', 'StaffTrainingEnrollment');
  orm.defineModel<StaffCertification>('staff_certifications', 'StaffCertification');
  orm.defineModel<StaffSkill>('staff_skills', 'StaffSkill');
  orm.defineModel<StaffEmployeeSkill>('staff_employee_skills', 'StaffEmployeeSkill');
  orm.defineModel<StaffDocument>('staff_documents', 'StaffDocument');
  orm.defineModel<StaffComplianceItem>('staff_compliance_items', 'StaffComplianceItem');
  orm.defineModel<StaffDisciplinaryAction>('staff_disciplinary_actions', 'StaffDisciplinaryAction');
  orm.defineModel<StaffExpenseReport>('staff_expense_reports', 'StaffExpenseReport');
  orm.defineModel<InventoryWarehouse>('inventory_warehouses', 'InventoryWarehouse');
  orm.defineModel<InventoryCategory>('inventory_categories', 'InventoryCategory');
  orm.defineModel<InventoryBrand>('inventory_brands', 'InventoryBrand');
  orm.defineModel<InventoryItem>('inventory_items', 'InventoryItem');
  orm.defineModel<InventoryVariant>('inventory_variants', 'InventoryVariant');
  orm.defineModel<InventoryStock>('inventory_stocks', 'InventoryStock');
  orm.defineModel<InventoryMovement>('inventory_movements', 'InventoryMovement');
  orm.defineModel<InventorySupplier>('inventory_suppliers', 'InventorySupplier');
  orm.defineModel<InventoryPurchaseOrder>('inventory_purchase_orders', 'InventoryPurchaseOrder');
  orm.defineModel<InventoryPurchaseOrderItem>('inventory_purchase_order_items', 'InventoryPurchaseOrderItem');
  orm.defineModel<InventoryGoodsReceivedNote>('inventory_goods_received_notes', 'InventoryGoodsReceivedNote');
  orm.defineModel<InventoryStockTransfer>('inventory_stock_transfers', 'InventoryStockTransfer');
  orm.defineModel<InventoryStockCount>('inventory_stock_counts', 'InventoryStockCount');
  orm.defineModel<InventoryReorderRule>('inventory_reorder_rules', 'InventoryReorderRule');
  orm.defineModel<InventoryBatch>('inventory_batches', 'InventoryBatch');
  orm.defineModel<InventoryReturn>('inventory_returns', 'InventoryReturn');
  orm.defineModel<InventoryCostHistory>('inventory_cost_histories', 'InventoryCostHistory');
  orm.defineModel<Task>('tasks', 'Task');
  orm.defineModel<DepartmentModule>('department_modules', 'DepartmentModule');
  orm.defineModel<DepartmentModuleAssignment>('department_module_assignments', 'DepartmentModuleAssignment');
} 